.then((res) => console.log(res))
.catch((err) => console.error(`${err} and catch`))